[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/",
]

# Compiler settings
solc_version = "0.8.21"
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing configuration
gas_reports = ["*"]
ffi = false

# Fuzz testing
[fuzz]
runs = 1000
max_test_rejects = 65536

# Invariant testing
[invariant]
runs = 256
depth = 15
fail_on_revert = false

# Swellchain network configurations
[rpc_endpoints]
swellchain = "https://swell-mainnet.alt.technology"
swellchain_testnet = "https://swell-testnet.alt.technology"
ethereum = "${ETHEREUM_RPC_URL}"

[etherscan]
swellchain = { key = "${SWELLCHAIN_ETHERSCAN_API_KEY}", url = "https://swellchainscan.io/api" }
ethereum = { key = "${ETHERSCAN_API_KEY}" } 